# Generated by Django 4.2.9 on 2024-02-24 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("grader", "0009_alter_content_content_comment_alter_content_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form_Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("expectation", models.CharField(max_length=255)),
                (
                    "time",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("votes", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="forumessay",
            name="content",
        ),
        migrations.RemoveField(
            model_name="forumessay",
            name="user",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="comment",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="grader.question",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Content",
        ),
        migrations.DeleteModel(
            name="ForumEssay",
        ),
        migrations.AddField(
            model_name="form_question",
            name="tags",
            field=models.ManyToManyField(to="grader.tag"),
        ),
        migrations.AddField(
            model_name="form_question",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
