# Generated by Django 4.2.9 on 2024-02-24 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("grader", "0012_alter_form_question_tags_alter_form_question_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="question",
        ),
        migrations.AddField(
            model_name="form_question",
            name="Comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="grader.comment",
            ),
        ),
    ]
