# Generated by Django 4.2.9 on 2024-02-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("grader", "0013_remove_comment_question_form_question_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form_question",
            name="Comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="grader.comment",
            ),
        ),
    ]
