# Generated by Django 4.2.9 on 2024-02-25 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("grader", "0014_alter_form_question_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form_question",
            name="tags",
        ),
        migrations.AddField(
            model_name="form_question",
            name="tags",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="grader.tag",
            ),
        ),
    ]
