# Generated by Django 4.2.9 on 2024-03-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grader", "0018_profile_date_of_birth_profile_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True, default="images/default.png", null=True, upload_to=""
            ),
        ),
    ]
