# Generated by Django 4.2.9 on 2024-03-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grader", "0020_alter_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact_info",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=10)),
                ("message", models.TextField()),
            ],
        ),
    ]
