# Generated by Django 4.2.9 on 2024-03-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grader", "0022_alter_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="picture",
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
