# Generated by Django 4.2.9 on 2024-03-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grader", "0023_remove_profile_picture_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(null=True, upload_to="mysite/grader/static/images"),
        ),
    ]
